//! GPU document canvas: an `egui_wgpu` paint callback that draws one document view with a custom
//! WGSL shader.
//!
//! The document's composite lives on the GPU as one or more mipmapped `Rgba8Unorm` textures
//! (premultiplied alpha, sRGB-encoded values, matching how the CPU path and egui blend). Uploads
//! are either full (new document, size change, re-render) or a damage rect (brush strokes); after
//! an upload only the affected region of each mip level is regenerated by a render-pass blit chain.
//! Documents larger than the device's maximum texture size are split into tiles.
//!
//! Per frame the shader draws, in *device pixels*:
//! - a soft analytic drop shadow around the document on the pasteboard (erf-blurred box),
//! - a screen-space transparency checkerboard (8 pt squares, grays 255/204) under the document,
//! - the document itself, sampled trilinearly when zoomed out, bilinearly between 1× and 2×, and
//!   with an anti-aliased "sharp nearest" filter at integer scales and ≥ 2×,
//! - a one-device-pixel pixel grid at zoom ≥ 8.
//!
//! GPU resources live in the renderer's `callback_resources` type map; the per-frame callback only
//! carries plain view parameters, so it is `Send + Sync` on every target (including wasm).
//!
//! The document pixels still come from the CPU compositor (`photocraft-compose`) for now; the wgpu
//! compositor (M5) will render straight into these tiles.

use std::collections::HashMap;
use std::num::NonZeroU64;

use eframe::egui_wgpu::{self, CallbackResources, CallbackTrait, RenderState, ScreenDescriptor};
use eframe::wgpu;
use eframe::wgpu::util::DeviceExt as _;

/// Default tile side; documents up to this size (and the device limit) use a single texture.
pub const DEFAULT_TILE: u32 = 8192;
const FORMAT: wgpu::TextureFormat = wgpu::TextureFormat::Rgba8Unorm;
const VIEW_UNIFORM_SIZE: u64 = 112;
const VIEW_FLOATS: usize = 28;
const TILE_UNIFORM_SIZE: u64 = 16;

/// Parameters for drawing one document view. Positions are in egui points.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct ViewParams {
    /// Document key used with [`GpuCanvas::upload_full`].
    pub doc: u64,
    /// Document size in pixels.
    pub doc_size: [u32; 2],
    /// Screen points per document pixel.
    pub zoom: f32,
    /// Document point shown at the centre of the canvas rect.
    pub center: [f32; 2],
    /// Draw the drop shadow on the pasteboard.
    pub shadow: bool,
    /// Draw the pixel grid at high zoom.
    pub pixel_grid: bool,
    /// Distinguishes views painted in the same frame (main canvas, extra windows).
    pub view_key: u64,
    /// Display transform: 0 none, 1 the document's display LUT (Proof Colors), 2 LUT plus the
    /// gamut warning (see [`GpuCanvas::set_display_lut`]).
    pub display: u8,
}

/// Uploads documents to the GPU and paints them. Cheap to clone.
#[derive(Clone)]
pub struct GpuCanvas {
    rs: RenderState,
    tile: u32,
}

impl GpuCanvas {
    /// Create pipelines and register resources with the egui renderer.
    pub fn new(rs: &RenderState) -> Self {
        Self::with_tile(rs, None)
    }

    /// Like [`GpuCanvas::new`] with a preferred texture tile side (`PHOTOCRAFT_GPU_TILE` wins).
    pub fn with_tile(rs: &RenderState, tile: Option<u32>) -> Self {
        let max = rs.device.limits().max_texture_dimension_2d;
        let env_tile = std::env::var("PHOTOCRAFT_GPU_TILE").ok().and_then(|v| v.parse::<u32>().ok());
        let tile = env_tile.or(tile).unwrap_or(DEFAULT_TILE).clamp(64, max);
        let res = Resources::new(&rs.device, &rs.queue, rs.target_format);
        rs.renderer.write().callback_resources.insert(res);
        log::info!("gpu canvas: target {:?}, max texture {max}, tile {tile}", rs.target_format);
        Self { rs: rs.clone(), tile }
    }

    /// Set the checkerboard and gamut warning colours.
    pub fn set_style(&self, style: CanvasStyle) {
        let mut r = self.rs.renderer.write();
        if let Some(res) = r.callback_resources.get_mut::<Resources>() {
            res.style = style;
        }
    }

    /// Whether document `doc` has been uploaded with this size.
    pub fn has(&self, doc: u64, size: [u32; 2]) -> bool {
        let r = self.rs.renderer.read();
        r.callback_resources.get::<Resources>().and_then(|res| res.docs.get(&doc)).is_some_and(|d| d.size == size)
    }

    /// Replace the whole document image. `rgba` is premultiplied RGBA8, `size[0] * size[1] * 4` bytes.
    pub fn upload_full(&self, doc: u64, size: [u32; 2], rgba: &[u8]) {
        assert_eq!(rgba.len(), size[0] as usize * size[1] as usize * 4, "upload_full: buffer size mismatch");
        if size[0] == 0 || size[1] == 0 {
            return;
        }
        let (device, queue) = (&self.rs.device, &self.rs.queue);
        let mut renderer = self.rs.renderer.write();
        let Some(res) = renderer.callback_resources.get_mut::<Resources>() else { return };
        if res.docs.get(&doc).is_none_or(|d| d.size != size) {
            let tex = DocTextures::new(device, res, size, self.tile);
            res.docs.insert(doc, tex);
        }
        let d = &res.docs[&doc];
        d.write(queue, [0, 0], size, size[0], rgba);
        d.regenerate_mips(device, queue, res, [0, 0, size[0], size[1]]);
    }

    /// Replace a rectangle `origin..origin+size` of an uploaded document with premultiplied RGBA8
    /// pixels (`size[0] * size[1] * 4` bytes). Returns false if the document isn't uploaded.
    pub fn upload_rect(&self, doc: u64, origin: [u32; 2], size: [u32; 2], rgba: &[u8]) -> bool {
        assert_eq!(rgba.len(), size[0] as usize * size[1] as usize * 4, "upload_rect: buffer size mismatch");
        let (device, queue) = (&self.rs.device, &self.rs.queue);
        let mut renderer = self.rs.renderer.write();
        let Some(res) = renderer.callback_resources.get_mut::<Resources>() else { return false };
        let Some(d) = res.docs.get(&doc) else { return false };
        if origin[0] + size[0] > d.size[0] || origin[1] + size[1] > d.size[1] {
            return false;
        }
        if size[0] == 0 || size[1] == 0 {
            return true;
        }
        d.write(queue, origin, size, size[0], rgba);
        d.regenerate_mips(device, queue, res, [origin[0], origin[1], origin[0] + size[0], origin[1] + size[1]]);
        true
    }

    /// Upload a CPU composite covering the whole document.
    pub fn upload_buffer_full(&self, doc: u64, buf: &photocraft_compose::Buffer) {
        let size = [buf.rect.width(), buf.rect.height()];
        self.upload_full(doc, size, &premultiply_rgba8(&buf.px));
    }

    /// Upload a CPU composite of a sub-rectangle (in document pixels, `buf.rect`).
    pub fn upload_buffer_rect(&self, doc: u64, buf: &photocraft_compose::Buffer) -> bool {
        let r = buf.rect;
        if r.x0 < 0 || r.y0 < 0 {
            return false;
        }
        self.upload_rect(doc, [r.x0 as u32, r.y0 as u32], [r.width(), r.height()], &premultiply_rgba8(&buf.px))
    }

    /// Composite `region` of `doc` with the wgpu compositor straight into its display texture
    /// (no CPU pixels, no upload of the composite). Returns `Err` when the document uses features
    /// the GPU compositor doesn't cover yet; the caller then falls back to the CPU compositor.
    pub fn composite(&self, doc: &photocraft_doc::Document, region: photocraft_geom::Rect) -> Result<photocraft_gpu::Stats, photocraft_gpu::Unsupported> {
        let (device, queue) = (&self.rs.device, &self.rs.queue);
        let size = [doc.size.width, doc.size.height];
        if size[0] == 0 || size[1] == 0 {
            return Err(photocraft_gpu::Unsupported("empty document".into()));
        }
        if std::env::var_os("PHOTOCRAFT_CPU_COMPOSE").is_some() {
            return Err(photocraft_gpu::Unsupported("disabled by PHOTOCRAFT_CPU_COMPOSE".into()));
        }
        let mut renderer = self.rs.renderer.write();
        let Some(res) = renderer.callback_resources.get_mut::<Resources>() else { return Err(photocraft_gpu::Unsupported("no GPU canvas".into())) };
        let mut comp = res.compositor.take().unwrap_or_else(|| photocraft_gpu::Compositor::new_with_format(device, photocraft_gpu::Compositor::preferred_acc_format(&self.rs.adapter)));
        let key = doc.id.0;
        let fresh = res.docs.get(&key).is_none_or(|d| d.size != size);
        let region = if fresh { doc.bounds() } else { region.intersect(&doc.bounds()) };
        if let Err(e) = comp.supports(doc) {
            res.compositor = Some(comp);
            return Err(e);
        }
        if fresh {
            let tex = DocTextures::new(device, res, size, self.tile);
            res.docs.insert(key, tex);
        }
        let d = &res.docs[&key];
        let (bgl, pipe) = (&res.encode_bgl, &res.encode_pipeline);
        let result = comp.render(device, queue, doc, region, |enc, out| {
            for t in &d.tiles {
                let [tx, ty, tw, th] = t.rect.map(|v| v as i32);
                let r = out.rect.intersect(&photocraft_geom::Rect::from_xywh(tx, ty, tw as u32, th as u32));
                if r.is_empty() {
                    continue;
                }
                let offset = [out.rect.x0 - tx, out.rect.y0 - ty, 0, 0];
                let ubuf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor { label: Some("pc_encode"), contents: &offset.iter().flat_map(|v| v.to_le_bytes()).collect::<Vec<u8>>(), usage: wgpu::BufferUsages::UNIFORM });
                let bg = device.create_bind_group(&wgpu::BindGroupDescriptor {
                    label: Some("pc_encode"),
                    layout: bgl,
                    entries: &[wgpu::BindGroupEntry { binding: 0, resource: wgpu::BindingResource::TextureView(out.view) }, wgpu::BindGroupEntry { binding: 1, resource: ubuf.as_entire_binding() }],
                });
                let mut pass = enc.begin_render_pass(&wgpu::RenderPassDescriptor {
                    label: Some("pc_encode"),
                    color_attachments: &[Some(wgpu::RenderPassColorAttachment { view: &t.levels[0], resolve_target: None, depth_slice: None, ops: wgpu::Operations { load: wgpu::LoadOp::Load, store: wgpu::StoreOp::Store } })],
                    depth_stencil_attachment: None,
                    timestamp_writes: None,
                    occlusion_query_set: None,
                    multiview_mask: None,
                });
                pass.set_pipeline(pipe);
                pass.set_bind_group(0, &bg, &[]);
                pass.set_scissor_rect((r.x0 - tx) as u32, (r.y0 - ty) as u32, r.width(), r.height());
                pass.draw(0..3, 0..1);
            }
        });
        if result.is_ok() {
            d.regenerate_mips(device, queue, res, [region.x0 as u32, region.y0 as u32, region.x1 as u32, region.y1 as u32]);
            if std::env::var_os("PHOTOCRAFT_GPU_SYNC").is_some() {
                // Benchmarking: wait for the GPU so callers can time the whole refresh.
                let _ = device.poll(wgpu::PollType::Wait { submission_index: None, timeout: None });
            }
        } else if fresh {
            res.docs.remove(&key);
        }
        res.compositor = Some(comp);
        result
    }

    /// Free textures of documents not in `live`.
    pub fn retain(&self, live: &[u64]) {
        let mut renderer = self.rs.renderer.write();
        if let Some(res) = renderer.callback_resources.get_mut::<Resources>()
            && res.docs.keys().any(|k| !live.contains(k))
        {
            let gone: Vec<u64> = res.docs.keys().filter(|k| !live.contains(k)).copied().collect();
            if let Some(c) = res.compositor.as_mut() {
                for k in &gone {
                    c.forget_doc(photocraft_doc::DocId(*k));
                }
            }
            res.docs.retain(|k, _| live.contains(k));
        }
    }

    /// Set (or clear with `None`) the display LUT of document `doc`: `size`³ RGBA8 texels, red
    /// fastest. RGB is the display colour for each lattice input; alpha 255 marks out-of-gamut
    /// colours for the gamut warning.
    pub fn set_display_lut(&self, doc: u64, size: u32, rgba: Option<&[u8]>) {
        let (device, queue) = (&self.rs.device, &self.rs.queue);
        let mut renderer = self.rs.renderer.write();
        let Some(res) = renderer.callback_resources.get_mut::<Resources>() else { return };
        match rgba {
            None => {
                res.luts.remove(&doc);
            }
            Some(bytes) => {
                assert_eq!(bytes.len(), (size * size * size * 4) as usize, "set_display_lut: buffer size mismatch");
                let bg = lut_bind_group(device, queue, &res.lut_bgl, size, bytes);
                res.luts.insert(doc, bg);
            }
        }
    }

    /// Add the paint callback drawing `params` into `rect` (clipped by the painter's clip rect).
    pub fn paint(painter: &egui::Painter, rect: egui::Rect, params: ViewParams) {
        painter.add(egui_wgpu::Callback::new_paint_callback(rect, CanvasCallback { rect, params }));
    }
}

/// Milliseconds since first call (monotonic). Always 0 on wasm, where `std::time` is unavailable.
pub fn now_ms() -> f64 {
    #[cfg(not(target_arch = "wasm32"))]
    {
        static START: std::sync::OnceLock<std::time::Instant> = std::sync::OnceLock::new();
        START.get_or_init(std::time::Instant::now).elapsed().as_secs_f64() * 1000.0
    }
    #[cfg(target_arch = "wasm32")]
    0.0
}

/// UI-thread timings (CPU side), exponentially smoothed.
#[derive(Clone, Debug, Default, serde::Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Perf {
    /// Average CPU time building the UI per frame (ms).
    pub ui_ms: f64,
    /// Worst UI frame of the last ~second (ms).
    pub ui_max_ms: f64,
    /// Last canvas refresh: CPU composite (ms).
    pub composite_ms: f64,
    /// Last canvas refresh: conversion + upload (ms).
    pub upload_ms: f64,
    /// Last canvas refresh kind: "full", "rect" or "none".
    pub last_refresh: &'static str,
    /// Pixels in the last refresh.
    pub last_refresh_px: u64,
    /// Whether the GPU canvas path is active.
    pub gpu: bool,
    /// Layer tiles uploaded by the last GPU composite.
    pub gpu_uploads: u64,
    /// Why the last refresh fell back to the CPU compositor (None = GPU composited).
    pub gpu_fallback: Option<String>,
    /// Last command run through the app and its duration (ms).
    pub last_command: String,
    pub command_ms: f64,
    /// Most recent cost of occasional UI work (outline tracing, thumbnails, …), in ms.
    pub spans: std::collections::BTreeMap<&'static str, f64>,
    #[serde(skip)]
    max_decay: f64,
}

impl Perf {
    pub fn record(&mut self, kind: &'static str, px: u64, composite_ms: f64, upload_ms: f64) {
        self.last_refresh = kind;
        self.last_refresh_px = px;
        self.composite_ms = composite_ms;
        self.upload_ms = upload_ms;
        if !kind.starts_with("gpu") {
            self.gpu_uploads = 0;
        } else {
            self.gpu_fallback = None;
        }
    }
    pub fn span(&mut self, name: &'static str, ms: f64) {
        self.spans.insert(name, (ms * 100.0).round() / 100.0);
    }
    pub fn frame(&mut self, ms: f64) {
        self.ui_ms = if self.ui_ms == 0.0 { ms } else { self.ui_ms * 0.9 + ms * 0.1 };
        self.max_decay += 1.0;
        if ms > self.ui_max_ms || self.max_decay > 60.0 {
            self.ui_max_ms = ms;
            self.max_decay = 0.0;
        }
    }
}

/// Straight-alpha f32 RGBA (sRGB-encoded) → premultiplied RGBA8, split across threads on native.
pub fn premultiply_rgba8(px: &[[f32; 4]]) -> Vec<u8> {
    fn convert(src: &[[f32; 4]], dst: &mut [u8]) {
        for (o, p) in dst.chunks_exact_mut(4).zip(src) {
            let a = p[3].clamp(0.0, 1.0);
            o[0] = (p[0].clamp(0.0, 1.0) * a * 255.0 + 0.5) as u8;
            o[1] = (p[1].clamp(0.0, 1.0) * a * 255.0 + 0.5) as u8;
            o[2] = (p[2].clamp(0.0, 1.0) * a * 255.0 + 0.5) as u8;
            o[3] = (a * 255.0 + 0.5) as u8;
        }
    }
    let mut out = vec![0u8; px.len() * 4];
    #[cfg(not(target_arch = "wasm32"))]
    if px.len() > 1 << 18 {
        let threads = std::thread::available_parallelism().map_or(4, |n| n.get()).min(16);
        let chunk = px.len().div_ceil(threads);
        std::thread::scope(|s| {
            for (src, dst) in px.chunks(chunk).zip(out.chunks_mut(chunk * 4)) {
                s.spawn(move || convert(src, dst));
            }
        });
        return out;
    }
    convert(px, &mut out);
    out
}

// ---------------------------------------------------------------------------------------------
// GPU resources

struct Resources {
    view_bgl: wgpu::BindGroupLayout,
    tile_bgl: wgpu::BindGroupLayout,
    shadow_pipeline: wgpu::RenderPipeline,
    tile_pipeline: wgpu::RenderPipeline,
    sampler: wgpu::Sampler,
    mip_bgl: wgpu::BindGroupLayout,
    mip_pipeline: wgpu::RenderPipeline,
    mip_sampler: wgpu::Sampler,
    docs: HashMap<u64, DocTextures>,
    views: HashMap<u64, ViewGpu>,
    out_linear: bool,
    /// The wgpu layer compositor (created on first use).
    compositor: Option<photocraft_gpu::Compositor>,
    encode_bgl: wgpu::BindGroupLayout,
    encode_pipeline: wgpu::RenderPipeline,
    lut_bgl: wgpu::BindGroupLayout,
    /// Display LUTs per document (Proof Colors / Gamut Warning); `identity_lut` otherwise.
    luts: HashMap<u64, wgpu::BindGroup>,
    identity_lut: wgpu::BindGroup,
    /// Transparency checkerboard and gamut warning colours (Preferences › Transparency & Gamut).
    style: CanvasStyle,
}

/// Canvas colours from Preferences › Transparency & Gamut.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct CanvasStyle {
    /// Checker square side in points (0 = no checkerboard: transparency shows white).
    pub checker_square: f32,
    pub checker_light: [f32; 3],
    pub checker_dark: [f32; 3],
    pub gamut_color: [f32; 3],
    /// Gamut warning opacity 0..1.
    pub gamut_opacity: f32,
}

impl Default for CanvasStyle {
    fn default() -> Self {
        Self { checker_square: 8.0, checker_light: [1.0; 3], checker_dark: [0.8; 3], gamut_color: [0.5; 3], gamut_opacity: 1.0 }
    }
}

/// A `size`³ RGBA8 3D texture bound for the canvas shader.
fn lut_bind_group(device: &wgpu::Device, queue: &wgpu::Queue, bgl: &wgpu::BindGroupLayout, size: u32, bytes: &[u8]) -> wgpu::BindGroup {
    let extent = wgpu::Extent3d { width: size, height: size, depth_or_array_layers: size };
    let texture = device.create_texture(&wgpu::TextureDescriptor {
        label: Some("pc_display_lut"),
        size: extent,
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D3,
        format: FORMAT,
        usage: wgpu::TextureUsages::TEXTURE_BINDING | wgpu::TextureUsages::COPY_DST,
        view_formats: &[],
    });
    queue.write_texture(
        wgpu::TexelCopyTextureInfo { texture: &texture, mip_level: 0, origin: wgpu::Origin3d::ZERO, aspect: wgpu::TextureAspect::All },
        bytes,
        wgpu::TexelCopyBufferLayout { offset: 0, bytes_per_row: Some(size * 4), rows_per_image: Some(size) },
        extent,
    );
    let view = texture.create_view(&wgpu::TextureViewDescriptor::default());
    device.create_bind_group(&wgpu::BindGroupDescriptor { label: Some("pc_display_lut"), layout: bgl, entries: &[wgpu::BindGroupEntry { binding: 0, resource: wgpu::BindingResource::TextureView(&view) }] })
}

/// The 2³ identity LUT (unused unless a document has none and `display` is set).
fn identity_lut_bytes() -> Vec<u8> {
    (0..8).flat_map(|i| [if i & 1 != 0 { 255 } else { 0 }, if i & 2 != 0 { 255 } else { 0 }, if i & 4 != 0 { 255 } else { 0 }, 0]).collect()
}

struct ViewGpu {
    buffer: wgpu::Buffer,
    bind_group: wgpu::BindGroup,
    frame_data: [f32; VIEW_FLOATS],
}

struct DocTextures {
    size: [u32; 2],
    tiles: Vec<Tile>,
}

struct Tile {
    /// Document-pixel rect: x, y, w, h.
    rect: [u32; 4],
    texture: wgpu::Texture,
    levels: Vec<wgpu::TextureView>,
    bind_group: wgpu::BindGroup,
    _uniform: wgpu::Buffer,
}

fn uniform_entry(binding: u32, size: u64, vis: wgpu::ShaderStages) -> wgpu::BindGroupLayoutEntry {
    wgpu::BindGroupLayoutEntry {
        binding,
        visibility: vis,
        ty: wgpu::BindingType::Buffer { ty: wgpu::BufferBindingType::Uniform, has_dynamic_offset: false, min_binding_size: NonZeroU64::new(size) },
        count: None,
    }
}
fn texture_entry(binding: u32) -> wgpu::BindGroupLayoutEntry {
    wgpu::BindGroupLayoutEntry {
        binding,
        visibility: wgpu::ShaderStages::FRAGMENT,
        ty: wgpu::BindingType::Texture { multisampled: false, sample_type: wgpu::TextureSampleType::Float { filterable: true }, view_dimension: wgpu::TextureViewDimension::D2 },
        count: None,
    }
}
fn sampler_entry(binding: u32) -> wgpu::BindGroupLayoutEntry {
    wgpu::BindGroupLayoutEntry { binding, visibility: wgpu::ShaderStages::FRAGMENT, ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering), count: None }
}

fn f32_bytes(v: &[f32]) -> Vec<u8> {
    v.iter().flat_map(|f| f.to_ne_bytes()).collect()
}

fn pipeline(device: &wgpu::Device, label: &str, layout: &wgpu::PipelineLayout, module: &wgpu::ShaderModule, (vs, fs): (&str, &str), format: wgpu::TextureFormat, blend: Option<wgpu::BlendState>) -> wgpu::RenderPipeline {
    device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
        label: Some(label),
        layout: Some(layout),
        vertex: wgpu::VertexState { module, entry_point: Some(vs), buffers: &[], compilation_options: Default::default() },
        primitive: wgpu::PrimitiveState { topology: wgpu::PrimitiveTopology::TriangleList, ..Default::default() },
        depth_stencil: None,
        multisample: wgpu::MultisampleState { count: 1, mask: !0, alpha_to_coverage_enabled: false },
        fragment: Some(wgpu::FragmentState { module, entry_point: Some(fs), targets: &[Some(wgpu::ColorTargetState { format, blend, write_mask: wgpu::ColorWrites::ALL })], compilation_options: Default::default() }),
        multiview_mask: None,
        cache: None,
    })
}

impl Resources {
    fn new(device: &wgpu::Device, queue: &wgpu::Queue, target: wgpu::TextureFormat) -> Self {
        let module = device.create_shader_module(wgpu::ShaderModuleDescriptor { label: Some("pc_canvas"), source: wgpu::ShaderSource::Wgsl(CANVAS_WGSL.into()) });
        let vis = wgpu::ShaderStages::VERTEX | wgpu::ShaderStages::FRAGMENT;
        let view_bgl = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor { label: Some("pc_canvas_view"), entries: &[uniform_entry(0, VIEW_UNIFORM_SIZE, vis), sampler_entry(1)] });
        let tile_bgl = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor { label: Some("pc_canvas_tile"), entries: &[texture_entry(0), uniform_entry(1, TILE_UNIFORM_SIZE, vis)] });
        let lut_entry = wgpu::BindGroupLayoutEntry {
            binding: 0,
            visibility: wgpu::ShaderStages::FRAGMENT,
            ty: wgpu::BindingType::Texture { multisampled: false, sample_type: wgpu::TextureSampleType::Float { filterable: true }, view_dimension: wgpu::TextureViewDimension::D3 },
            count: None,
        };
        let lut_bgl = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor { label: Some("pc_display_lut"), entries: &[lut_entry] });
        let layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor { label: Some("pc_canvas"), bind_group_layouts: &[Some(&view_bgl), Some(&tile_bgl), Some(&lut_bgl)], immediate_size: 0 });
        let shadow_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor { label: Some("pc_canvas_shadow"), bind_group_layouts: &[Some(&view_bgl)], immediate_size: 0 });
        // Premultiplied "over", with egui's alpha rule (keeps a transparent window's alpha sane).
        let blend = wgpu::BlendState {
            color: wgpu::BlendComponent { src_factor: wgpu::BlendFactor::One, dst_factor: wgpu::BlendFactor::OneMinusSrcAlpha, operation: wgpu::BlendOperation::Add },
            alpha: wgpu::BlendComponent { src_factor: wgpu::BlendFactor::OneMinusDstAlpha, dst_factor: wgpu::BlendFactor::One, operation: wgpu::BlendOperation::Add },
        };
        let shadow_pipeline = pipeline(device, "pc_canvas_shadow", &shadow_layout, &module, ("vs_shadow", "fs_shadow"), target, Some(blend));
        let tile_pipeline = pipeline(device, "pc_canvas_tile", &layout, &module, ("vs_tile", "fs_tile"), target, Some(blend));
        let sampler = device.create_sampler(&wgpu::SamplerDescriptor {
            label: Some("pc_canvas_trilinear"),
            mag_filter: wgpu::FilterMode::Linear,
            min_filter: wgpu::FilterMode::Linear,
            mipmap_filter: wgpu::MipmapFilterMode::Linear,
            ..Default::default()
        });

        let mip_module = device.create_shader_module(wgpu::ShaderModuleDescriptor { label: Some("pc_mip"), source: wgpu::ShaderSource::Wgsl(MIP_WGSL.into()) });
        let mip_bgl = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor { label: Some("pc_mip"), entries: &[texture_entry(0), sampler_entry(1)] });
        let mip_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor { label: Some("pc_mip"), bind_group_layouts: &[Some(&mip_bgl)], immediate_size: 0 });
        let mip_pipeline = pipeline(device, "pc_mip", &mip_layout, &mip_module, ("vs", "fs"), FORMAT, None);
        let mip_sampler = device.create_sampler(&wgpu::SamplerDescriptor { label: Some("pc_mip"), mag_filter: wgpu::FilterMode::Linear, min_filter: wgpu::FilterMode::Linear, ..Default::default() });
        // Compositor output (straight RGBA32F chunk) -> premultiplied RGBA8 display tile.
        let encode_module = device.create_shader_module(wgpu::ShaderModuleDescriptor { label: Some("pc_encode"), source: wgpu::ShaderSource::Wgsl(ENCODE_WGSL.into()) });
        let unfilterable = wgpu::BindGroupLayoutEntry {
            binding: 0,
            visibility: wgpu::ShaderStages::FRAGMENT,
            ty: wgpu::BindingType::Texture { multisampled: false, sample_type: wgpu::TextureSampleType::Float { filterable: false }, view_dimension: wgpu::TextureViewDimension::D2 },
            count: None,
        };
        let encode_bgl = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor { label: Some("pc_encode"), entries: &[unfilterable, uniform_entry(1, 16, wgpu::ShaderStages::FRAGMENT)] });
        let encode_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor { label: Some("pc_encode"), bind_group_layouts: &[Some(&encode_bgl)], immediate_size: 0 });
        let encode_pipeline = pipeline(device, "pc_encode", &encode_layout, &encode_module, ("vs", "fs"), FORMAT, None);
        let identity_lut = lut_bind_group(device, queue, &lut_bgl, 2, &identity_lut_bytes());
        Self {
            lut_bgl,
            luts: HashMap::new(),
            identity_lut,
            style: CanvasStyle::default(),
            view_bgl,
            tile_bgl,
            shadow_pipeline,
            tile_pipeline,
            sampler,
            mip_bgl,
            mip_pipeline,
            mip_sampler,
            docs: HashMap::new(),
            views: HashMap::new(),
            out_linear: target.is_srgb(),
            compositor: None,
            encode_bgl,
            encode_pipeline,
        }
    }
}

fn mip_count(w: u32, h: u32) -> u32 {
    32 - w.max(h).max(1).leading_zeros()
}

impl DocTextures {
    fn new(device: &wgpu::Device, res: &Resources, size: [u32; 2], tile: u32) -> Self {
        let mut tiles = Vec::new();
        for ty in (0..size[1]).step_by(tile as usize) {
            for tx in (0..size[0]).step_by(tile as usize) {
                let (w, h) = (tile.min(size[0] - tx), tile.min(size[1] - ty));
                let levels_n = mip_count(w, h);
                let texture = device.create_texture(&wgpu::TextureDescriptor {
                    label: Some("pc_canvas_tile"),
                    size: wgpu::Extent3d { width: w, height: h, depth_or_array_layers: 1 },
                    mip_level_count: levels_n,
                    sample_count: 1,
                    dimension: wgpu::TextureDimension::D2,
                    format: FORMAT,
                    usage: wgpu::TextureUsages::TEXTURE_BINDING | wgpu::TextureUsages::COPY_DST | wgpu::TextureUsages::RENDER_ATTACHMENT,
                    view_formats: &[],
                });
                let levels = (0..levels_n).map(|l| texture.create_view(&wgpu::TextureViewDescriptor { base_mip_level: l, mip_level_count: Some(1), ..Default::default() })).collect();
                let full = texture.create_view(&wgpu::TextureViewDescriptor::default());
                let uniform = device.create_buffer_init(&wgpu::util::BufferInitDescriptor { label: Some("pc_canvas_tile"), contents: &f32_bytes(&[tx as f32, ty as f32, w as f32, h as f32]), usage: wgpu::BufferUsages::UNIFORM });
                let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
                    label: Some("pc_canvas_tile"),
                    layout: &res.tile_bgl,
                    entries: &[wgpu::BindGroupEntry { binding: 0, resource: wgpu::BindingResource::TextureView(&full) }, wgpu::BindGroupEntry { binding: 1, resource: uniform.as_entire_binding() }],
                });
                tiles.push(Tile { rect: [tx, ty, w, h], texture, levels, bind_group, _uniform: uniform });
            }
        }
        Self { size, tiles }
    }

    /// Write `size` pixels at document `origin` from `rgba` (row stride `stride` pixels) into every
    /// overlapping tile's level 0.
    fn write(&self, queue: &wgpu::Queue, origin: [u32; 2], size: [u32; 2], stride: u32, rgba: &[u8]) {
        let (x0, y0, x1, y1) = (origin[0], origin[1], origin[0] + size[0], origin[1] + size[1]);
        for t in &self.tiles {
            let [tx, ty, tw, th] = t.rect;
            let (ix0, iy0, ix1, iy1) = (x0.max(tx), y0.max(ty), x1.min(tx + tw), y1.min(ty + th));
            if ix0 >= ix1 || iy0 >= iy1 {
                continue;
            }
            let offset = ((iy0 - y0) as u64 * stride as u64 + (ix0 - x0) as u64) * 4;
            queue.write_texture(
                wgpu::TexelCopyTextureInfo { texture: &t.texture, mip_level: 0, origin: wgpu::Origin3d { x: ix0 - tx, y: iy0 - ty, z: 0 }, aspect: wgpu::TextureAspect::All },
                rgba,
                wgpu::TexelCopyBufferLayout { offset, bytes_per_row: Some(stride * 4), rows_per_image: Some(iy1 - iy0) },
                wgpu::Extent3d { width: ix1 - ix0, height: iy1 - iy0, depth_or_array_layers: 1 },
            );
        }
    }

    /// Rebuild the mip chain inside document rect `r` (x0, y0, x1, y1) with 2×2 box filtering.
    fn regenerate_mips(&self, device: &wgpu::Device, queue: &wgpu::Queue, res: &Resources, r: [u32; 4]) {
        let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor { label: Some("pc_mips") });
        for t in &self.tiles {
            let [tx, ty, tw, th] = t.rect;
            let (mut x0, mut y0, mut x1, mut y1) = (r[0].max(tx), r[1].max(ty), r[2].min(tx + tw), r[3].min(ty + th));
            if x0 >= x1 || y0 >= y1 {
                continue;
            }
            (x0, y0, x1, y1) = (x0 - tx, y0 - ty, x1 - tx, y1 - ty);
            for level in 1..t.levels.len() {
                let (lw, lh) = ((tw >> level).max(1), (th >> level).max(1));
                // Damage at this level, padded by one texel for odd-size rounding.
                (x0, y0) = ((x0 / 2).saturating_sub(1), (y0 / 2).saturating_sub(1));
                (x1, y1) = ((x1.div_ceil(2) + 1).min(lw), (y1.div_ceil(2) + 1).min(lh));
                let bg = device.create_bind_group(&wgpu::BindGroupDescriptor {
                    label: Some("pc_mip"),
                    layout: &res.mip_bgl,
                    entries: &[wgpu::BindGroupEntry { binding: 0, resource: wgpu::BindingResource::TextureView(&t.levels[level - 1]) }, wgpu::BindGroupEntry { binding: 1, resource: wgpu::BindingResource::Sampler(&res.mip_sampler) }],
                });
                let mut pass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                    label: Some("pc_mip"),
                    color_attachments: &[Some(wgpu::RenderPassColorAttachment { view: &t.levels[level], resolve_target: None, depth_slice: None, ops: wgpu::Operations { load: wgpu::LoadOp::Load, store: wgpu::StoreOp::Store } })],
                    depth_stencil_attachment: None,
                    timestamp_writes: None,
                    occlusion_query_set: None,
                    multiview_mask: None,
                });
                pass.set_pipeline(&res.mip_pipeline);
                pass.set_bind_group(0, &bg, &[]);
                pass.set_scissor_rect(x0, y0, x1 - x0, y1 - y0);
                pass.draw(0..3, 0..1);
            }
        }
        queue.submit([encoder.finish()]);
    }
}

// ---------------------------------------------------------------------------------------------
// Per-frame callback

struct CanvasCallback {
    rect: egui::Rect,
    params: ViewParams,
}

/// Sampling mode: 0 trilinear, 1 bilinear, 2 anti-aliased nearest.
fn filter_mode(scale: f32) -> (f32, f32) {
    if scale < 0.999 {
        (0.0, (-scale.log2()).max(0.0))
    } else if (scale - scale.round()).abs() < 1e-3 || scale >= 2.0 {
        (2.0, 0.0)
    } else {
        (1.0, 0.0)
    }
}

impl CanvasCallback {
    /// Screen-pixel origin of document (0, 0) (snapped to whole pixels) and device px per doc px.
    fn placement(&self, ppp: f32) -> ([f32; 2], f32) {
        let p = &self.params;
        let scale = p.zoom * ppp;
        let c = self.rect.center();
        let ox = (c.x * ppp - p.center[0] * scale).round();
        let oy = (c.y * ppp - p.center[1] * scale).round();
        ([ox, oy], scale)
    }

    fn uniforms(&self, screen: [u32; 2], ppp: f32, out_linear: bool, style: &CanvasStyle) -> [f32; VIEW_FLOATS] {
        let p = &self.params;
        let (origin, scale) = self.placement(ppp);
        let (mode, lod) = filter_mode(scale);
        let grid = if p.pixel_grid && p.zoom >= 8.0 { 0.16 } else { 0.0 };
        let square = if style.checker_square > 0.0 { (style.checker_square * ppp).round().max(1.0) } else { 0.0 };
        let (l, d, g) = (style.checker_light, style.checker_dark, style.gamut_color);
        [
            screen[0] as f32, screen[1] as f32, scale, ppp,
            origin[0], origin[1], p.doc_size[0] as f32, p.doc_size[1] as f32,
            mode, lod, grid, square,
            (self.rect.min.x * ppp).round(), (self.rect.min.y * ppp).round(), p.display as f32, if out_linear { 1.0 } else { 0.0 },
            l[0], l[1], l[2], style.gamut_opacity,
            d[0], d[1], d[2], 0.0,
            g[0], g[1], g[2], 0.0,
        ]
    }
}

impl CallbackTrait for CanvasCallback {
    fn prepare(&self, device: &wgpu::Device, queue: &wgpu::Queue, screen: &ScreenDescriptor, _encoder: &mut wgpu::CommandEncoder, resources: &mut CallbackResources) -> Vec<wgpu::CommandBuffer> {
        let Some(res) = resources.get_mut::<Resources>() else { return Vec::new() };
        let data = self.uniforms(screen.size_in_pixels, screen.pixels_per_point, res.out_linear, &res.style);
        let (bgl, sampler) = (&res.view_bgl, &res.sampler);
        let v = res.views.entry(self.params.view_key).or_insert_with(|| {
            let buffer = device.create_buffer(&wgpu::BufferDescriptor { label: Some("pc_canvas_view"), size: VIEW_UNIFORM_SIZE, usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST, mapped_at_creation: false });
            let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
                label: Some("pc_canvas_view"),
                layout: bgl,
                entries: &[wgpu::BindGroupEntry { binding: 0, resource: buffer.as_entire_binding() }, wgpu::BindGroupEntry { binding: 1, resource: wgpu::BindingResource::Sampler(sampler) }],
            });
            ViewGpu { buffer, bind_group, frame_data: [f32::NAN; VIEW_FLOATS] }
        });
        if v.frame_data != data {
            queue.write_buffer(&v.buffer, 0, &f32_bytes(&data));
            v.frame_data = data;
        }
        Vec::new()
    }

    fn paint(&self, info: egui::PaintCallbackInfo, pass: &mut wgpu::RenderPass<'static>, resources: &CallbackResources) {
        let Some(res) = resources.get::<Resources>() else { return };
        let Some(view) = res.views.get(&self.params.view_key) else { return };
        let [sw, sh] = info.screen_size_px;
        let clip = info.clip_rect_in_pixels();
        if clip.width_px <= 0 || clip.height_px <= 0 || sw == 0 || sh == 0 {
            return;
        }
        // Work in whole-screen pixel coordinates; the scissor does the clipping.
        pass.set_viewport(0.0, 0.0, sw as f32, sh as f32, 0.0, 1.0);
        pass.set_scissor_rect(clip.left_px.max(0) as u32, clip.top_px.max(0) as u32, clip.width_px as u32, clip.height_px as u32);
        pass.set_bind_group(0, &view.bind_group, &[]);
        if self.params.shadow {
            pass.set_pipeline(&res.shadow_pipeline);
            pass.draw(0..6, 0..1);
        }
        let Some(doc) = res.docs.get(&self.params.doc) else { return };
        if doc.size != self.params.doc_size {
            return;
        }
        let (origin, scale) = self.placement(info.pixels_per_point);
        let (cx0, cy0) = (clip.left_px as f32, clip.top_px as f32);
        let (cx1, cy1) = (cx0 + clip.width_px as f32, cy0 + clip.height_px as f32);
        pass.set_pipeline(&res.tile_pipeline);
        pass.set_bind_group(2, res.luts.get(&self.params.doc).unwrap_or(&res.identity_lut), &[]);
        for t in &doc.tiles {
            let [tx, ty, tw, th] = t.rect.map(|v| v as f32);
            let (x0, y0) = (origin[0] + tx * scale, origin[1] + ty * scale);
            let (x1, y1) = (x0 + tw * scale, y0 + th * scale);
            if x1 < cx0 || y1 < cy0 || x0 > cx1 || y0 > cy1 {
                continue;
            }
            pass.set_bind_group(1, &t.bind_group, &[]);
            pass.draw(0..6, 0..1);
        }
    }
}

const CANVAS_WGSL: &str = r#"
struct View {
    a: vec4<f32>, // screen_w, screen_h, scale (device px per doc px), pixels_per_point
    b: vec4<f32>, // doc origin x, y (device px), doc w, h (doc px)
    c: vec4<f32>, // filter mode, lod, grid alpha, checker square (device px)
    d: vec4<f32>, // checker anchor x, y (device px), display (0 none, 1 LUT, 2 LUT + gamut), output linear
    e: vec4<f32>, // checker light rgb, gamut warning opacity
    f: vec4<f32>, // checker dark rgb
    g: vec4<f32>, // gamut warning rgb
};
struct Tile { r: vec4<f32> }; // x, y, w, h in doc px

@group(0) @binding(0) var<uniform> view: View;
@group(0) @binding(1) var samp: sampler;
@group(1) @binding(0) var tex: texture_2d<f32>;
@group(1) @binding(1) var<uniform> tile: Tile;
@group(2) @binding(0) var lut: texture_3d<f32>;

struct VOut { @builtin(position) pos: vec4<f32> };

fn corner(i: u32) -> vec2<f32> {
    var c = array<vec2<f32>, 6>(vec2(0.0, 0.0), vec2(1.0, 0.0), vec2(0.0, 1.0), vec2(0.0, 1.0), vec2(1.0, 0.0), vec2(1.0, 1.0));
    return c[i];
}

fn px_to_clip(p: vec2<f32>) -> vec4<f32> {
    let n = p / view.a.xy * 2.0 - 1.0;
    return vec4(n.x, -n.y, 0.0, 1.0);
}

fn doc_min() -> vec2<f32> { return view.b.xy; }
fn doc_max() -> vec2<f32> { return view.b.xy + view.b.zw * view.a.z; }

fn srgb_to_linear(c: vec3<f32>) -> vec3<f32> {
    let lo = c / 12.92;
    let hi = pow((c + 0.055) / 1.055, vec3(2.4));
    return select(hi, lo, c <= vec3(0.04045));
}

// --- drop shadow ---------------------------------------------------------------------------

fn erf2(x: vec2<f32>) -> vec2<f32> {
    let s = sign(x);
    let a = abs(x);
    var t = 1.0 + (0.278393 + (0.230389 + 0.078108 * (a * a)) * a) * a;
    t = t * t;
    return s - s / (t * t);
}

// Coverage of the box [lo, hi] blurred by a Gaussian of std-dev `sigma`, at point p.
fn box_blur(p: vec2<f32>, lo: vec2<f32>, hi: vec2<f32>, sigma: f32) -> f32 {
    let k = 0.70710678 / sigma;
    let q = (erf2((p - lo) * k) - erf2((p - hi) * k)) * 0.5;
    return q.x * q.y;
}

@vertex
fn vs_shadow(@builtin(vertex_index) vi: u32) -> VOut {
    let pad = 64.0 * view.a.w;
    let p = mix(doc_min() - vec2(pad), doc_max() + vec2(pad), corner(vi));
    return VOut(px_to_clip(p));
}

@fragment
fn fs_shadow(in: VOut) -> @location(0) vec4<f32> {
    let p = in.pos.xy;
    let lo = doc_min();
    let hi = doc_max();
    if (all(p >= lo) && all(p < hi)) {
        discard;
    }
    let u = view.a.w;
    let ambient = box_blur(p - vec2(0.0, 7.0 * u), lo, hi, 16.0 * u) * 0.40;
    let contact = box_blur(p - vec2(0.0, 0.75 * u), lo, hi, 1.25 * u) * 0.30;
    let a = 1.0 - (1.0 - ambient) * (1.0 - contact);
    return vec4(0.0, 0.0, 0.0, a);
}

// --- document tiles ------------------------------------------------------------------------

@vertex
fn vs_tile(@builtin(vertex_index) vi: u32) -> VOut {
    let p = view.b.xy + (tile.r.xy + tile.r.zw * corner(vi)) * view.a.z;
    return VOut(px_to_clip(p));
}

fn checker(p: vec2<f32>) -> vec3<f32> {
    if (view.c.w <= 0.0) {
        return vec3(1.0);
    }
    let c = floor((p - view.d.xy) / view.c.w);
    let odd = fract((c.x + c.y) * 0.5) > 0.25;
    return select(view.e.xyz, view.f.xyz, odd);
}

@fragment
fn fs_tile(in: VOut) -> @location(0) vec4<f32> {
    let p = in.pos.xy;
    let scale = view.a.z;
    let d = (p - view.b.xy) / scale;       // document pixel coordinates
    let size = tile.r.zw;
    let t = d - tile.r.xy;                 // texel coordinates within this tile
    let mode = view.c.x;
    var col: vec4<f32>;
    if (mode < 0.5) {
        // Zoomed out: trilinear through the mip chain.
        col = textureSampleLevel(tex, samp, t / size, view.c.y);
    } else if (mode < 1.5) {
        col = textureSampleLevel(tex, samp, t / size, 0.0);
    } else {
        // Crisp texels with a one-device-pixel anti-aliased edge ("sharp bilinear").
        let tt = t - 0.5;
        let i = floor(tt);
        let f = clamp((tt - i - 0.5) * scale + 0.5, vec2(0.0), vec2(1.0));
        col = textureSampleLevel(tex, samp, (i + 0.5 + f) / size, 0.0);
    }
    if (view.d.z > 0.5 && col.a > 0.0) {
        // Proof Colors / Gamut Warning: the document's display LUT (alpha flags out-of-gamut).
        let n = f32(textureDimensions(lut).x);
        let c = clamp(col.rgb / col.a, vec3(0.0), vec3(1.0));
        let l = textureSampleLevel(lut, samp, (c * (n - 1.0) + 0.5) / n, 0.0);
        let shown = select(l.rgb, mix(l.rgb, view.g.xyz, view.e.w), view.d.z > 1.5 && l.a > 0.5);
        col = vec4(shown * col.a, col.a);
    }
    var rgb = col.rgb + checker(p) * (1.0 - col.a);
    let grid = view.c.z;
    if (grid > 0.0) {
        let e = fract(d) * scale;
        if (e.x < 1.0 || e.y < 1.0) {
            let l = dot(rgb, vec3(0.299, 0.587, 0.114));
            rgb = mix(rgb, select(vec3(1.0), vec3(0.0), l > 0.55), grid);
        }
    }
    if (view.d.w > 0.5) {
        rgb = srgb_to_linear(rgb);
    }
    return vec4(rgb, 1.0);
}
"#;

const ENCODE_WGSL: &str = r#"
@group(0) @binding(0) var acc: texture_2d<f32>;
@group(0) @binding(1) var<uniform> offset: vec4<i32>;

@vertex
fn vs(@builtin(vertex_index) vi: u32) -> @builtin(position) vec4<f32> {
    let uv = vec2(f32((vi << 1u) & 2u), f32(vi & 2u));
    return vec4(uv.x * 2.0 - 1.0, 1.0 - uv.y * 2.0, 0.0, 1.0);
}

@fragment
fn fs(@builtin(position) pos: vec4<f32>) -> @location(0) vec4<f32> {
    let c = textureLoad(acc, vec2<i32>(floor(pos.xy)) - offset.xy, 0);
    let a = clamp(c.a, 0.0, 1.0);
    return vec4(clamp(c.rgb, vec3(0.0), vec3(1.0)) * a, a);
}
"#;

const MIP_WGSL: &str = r#"
@group(0) @binding(0) var src: texture_2d<f32>;
@group(0) @binding(1) var samp: sampler;

struct V { @builtin(position) pos: vec4<f32>, @location(0) uv: vec2<f32> };

@vertex
fn vs(@builtin(vertex_index) vi: u32) -> V {
    let uv = vec2(f32((vi << 1u) & 2u), f32(vi & 2u));
    return V(vec4(uv.x * 2.0 - 1.0, 1.0 - uv.y * 2.0, 0.0, 1.0), uv);
}

@fragment
fn fs(in: V) -> @location(0) vec4<f32> {
    // A bilinear tap at the destination texel centre averages the 2×2 source block.
    return textureSampleLevel(src, samp, in.uv, 0.0);
}
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn filter_modes() {
        assert_eq!(filter_mode(0.25), (0.0, 2.0));
        assert_eq!(filter_mode(1.0).0, 2.0);
        assert_eq!(filter_mode(1.5).0, 1.0);
        assert_eq!(filter_mode(3.3).0, 2.0);
    }

    #[test]
    fn mips_and_premultiply() {
        assert_eq!(mip_count(1, 1), 1);
        assert_eq!(mip_count(4096, 100), 13);
        assert_eq!(mip_count(5, 3), 3);
        assert_eq!(premultiply_rgba8(&[[1.0, 0.5, 0.0, 0.5]]), vec![128, 64, 0, 128]);
    }

    #[cfg(not(target_arch = "wasm32"))]
    #[test]
    fn shaders_validate() {
        use wgpu::naga;
        for (name, src) in [("canvas", CANVAS_WGSL), ("mip", MIP_WGSL), ("encode", ENCODE_WGSL)] {
            let module = naga::front::wgsl::parse_str(src).unwrap_or_else(|e| panic!("{name}: {}", e.emit_to_string(src)));
            naga::valid::Validator::new(naga::valid::ValidationFlags::all(), naga::valid::Capabilities::empty()).validate(&module).unwrap_or_else(|e| panic!("{name}: {e:?}"));
        }
    }
}
